### ISSUE TITLE
Are any ABCD relevant redirects from any of the TDWG domains needed?

### ISSUE THREAD

**Issue by mdoering** [tdwg/abcd#1]
Does ABCD need to have any redirects (see https://github.com/tdwg/infrastructure/issues/4) from rs.tdwg.org or any other tdwg domain?

**Comment by jholetschek** [comment]
Hi Markus... what about
http://www.tdwg.org/schemas/abcd/ and
http://rs.tdwg.org/abcd/?

**Comment by WalterBerendsohn** [comment]
Hello,
I don’t know if this page is to be moved:
http://www.tdwg.org/standards/115/
It is marked as “permanent URL”, so it should be maintained.

And I suppose that the wiki-pages are kept (http://wiki.tdwg.org/ABCD/)? The documentation items there have been cited in publications.

Cheers
Walter

**Comment by mdoering** [comment]
The permanent http://www.tdwg.org/standards/115/ URL is maintained and will be redirected to the github repository (which is mostly rendered by the [README.md](https://github.com/tdwg/abcd/blob/master/README.md) file)

Apart from that and the wiki content itself there is http://rs.tdwg.org/abcd/ to be redirected.
Is there a need to also maintain http://www.tdwg.org/schemas/abcd/ which is the exact same content as rs.tdwg.org/abcd/ has? All links from the www subdomain do actually refer to the rs subdomain. It seems to me we should only maintain the rs subdomain which should redirect to a github pages branch of this abcd repository. The RDDL index file is already in this repository at https://github.com/tdwg/abcd/blob/master/ABCD_v206.html, but we also need all the other linked bits from the SVN repository. 

As an example the TAPIR repo has already a published [github pages branch](https://github.com/tdwg/tapir/tree/gh-pages) which was branched from the [master branch](https://github.com/tdwg/tapir). We can then redirect http://rs.tdwg.org/tapir/1.0/ to http://tdwg.github.io/tapir/

**Comment by mdoering** [comment]
I ahve created a github pages branch for abcd which can be updated once we have the svn code migrated: https://github.com/tdwg/abcd/tree/gh-pages which is published here: http://tdwg.github.io/abcd/ABCD_v206.html

**Comment by pmergen** [comment]
Hi
finally a bit of time to look into this. Not sure if it is me to not use GitHub as it should, but the Readme file and abstract of the standard when entering this ABCD instance seems odd and incomplete. The big title "Preferred Citation" shows at the end of the abstract but there is nothing more underneath ? 
Is this a bug or supposed to be so ? Did I miss an expand button somewhere ?

**Comment by mdoering** [comment]
Patricia, the migration is not yet done, so the readme is incomplete

**Comment by pmergen** [comment]
ah ok ;) was too hasty

Pat

**Comment by peterdesmet** [comment]
I've now added a preferred citation:

> Access to Biological Collections Data task group. 2007. Access to Biological Collection Data (ABCD), Release 2.06. Biodiversity Information Standards (TDWG) http://www.tdwg.org/standards/115

As I did not know the authors, I have used the task group as the author. This can be changed. I'll now create a release.

**Comment by peterdesmet** [comment]
Release is available at https://github.com/tdwg/abcd/releases/tag/2.06

We can (and should) still update the standard or its metadata, but those changes will not be included in the release.
