### ISSUE TITLE
Version 3.0 is missing

### ISSUE THREAD

**Issue by qgroom** [tdwg/abcd#10]
Version 3 of ABCD has been released, but the schema is missing from here and difficult to find.

**Comment by DavidFichtmueller** [comment]
Hey Quentin, thanks for pointing this out. With the updates to https://abcd.tdwg.org we moved the documentation and files to the gh-pages branch, but forgot to update the master branch as well. So I now updated it to contain the files of the standard while pointing to the documentation page for details.

**Comment by qgroom** [comment]
Hi @DavidFichtmueller ,
I don't know GitHub very well, but I thought you would create a new release for V3.0. 
Now if you go to the releases tab it says you are on 2.06 https://github.com/tdwg/abcd/releases
Quentin
