### ISSUE TITLE
Links to rs.tdwg.org/abcd return 404

### ISSUE THREAD

**Issue by stijnvanhoey** [tdwg/abcd#4]
On http://tdwg.github.io/abcd/ABCD_v206.html I clicked the first link (http://rs.tdwg.org/abcd/) and noticed it returns a 404. Does http//rs.tdwg.org/abcd still exist?

**Comment by peterdesmet** [comment]
Seems like a task for the @tdwg/infrastructure!

**Comment by mdoering** [comment]
The rs.tdwg.org vhost does not yet cover the abcd path, just abcd2:
https://github.com/tdwg/infrastructure/blob/master/vhosts/rs.tdwg.org.conf#L103

I will rewrite all requests to http://rs.tdwg.org/abcd/ to http://tdwg.github.io/abcd/ instead

**Comment by DavidFichtmueller** [comment]
The ProxyPass works as well. No need for my pull request then. Thanks.
