### ISSUE TITLE
ABCD homepage links to dead wiki

### ISSUE THREAD

**Issue by mdoering** [tdwg/abcd#7]
From http://www.tdwg.org/activities/abcd
to dead http://wiki.tdwg.org/ABCD/

The dead link also exists in the RDDL managed in this repo:
http://tdwg.github.io/abcd/ABCD_v206.html

**Comment by MattBlissett** [comment]
I've merged the change and restarted the server — this did indeed get overlooked while I was on holiday.

**Comment by DavidFichtmueller** [comment]
Thanks and no problem about the delay.
